# Generated by Django 6.0.1 on 2026-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50)),
                ('updated', models.CharField(blank=True, max_length=50)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('epic_id', models.CharField(blank=True, max_length=50, null=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.CharField(blank=True, max_length=50)),
                ('schedule_start', models.CharField(blank=True, max_length=50)),
                ('schedule_end', models.CharField(blank=True, max_length=50)),
                ('file_path', models.CharField(max_length=500, unique=True)),
                ('file_mtime', models.FloatField()),
                ('metadata_json', models.TextField()),
            ],
            options={
                'db_table': 'entities',
                'indexes': [models.Index(fields=['type'], name='entities_type_3f73d9_idx'), models.Index(fields=['status'], name='entities_status_1c41cf_idx'), models.Index(fields=['due_date'], name='entities_due_dat_e4eacf_idx'), models.Index(fields=['project_id'], name='entities_project_1dbbf6_idx'), models.Index(fields=['updated'], name='entities_updated_d9acc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('timestamp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'updates',
                'indexes': [models.Index(fields=['entity_id'], name='updates_entity__6ac1db_idx'), models.Index(fields=['timestamp'], name='updates_timesta_a8d4cb_idx')],
            },
        ),
    ]
