# Generated by Django 6.0.1 on 2026-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_populate_metadata_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entity',
            new_name='entities_status__c0e5d0_idx',
            old_name='entities_status_fk_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='entities_due_dat_e78f58_idx',
            old_name='entities_due_date_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='entities_archive_3148d6_idx',
            old_name='entities_archived_idx',
        ),
        migrations.RenameIndex(
            model_name='entity',
            new_name='entities_seq_id_2c53b6_idx',
            old_name='entities_seq_id_idx',
        ),
        migrations.RenameIndex(
            model_name='entitylabel',
            new_name='entity_labe_entity__24286c_idx',
            old_name='entity_labels_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='entitylabel',
            new_name='entity_labe_label_i_c81544_idx',
            old_name='entity_labels_label_idx',
        ),
        migrations.RenameIndex(
            model_name='entityperson',
            new_name='entity_pers_entity__9ace1c_idx',
            old_name='entity_persons_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='entityperson',
            new_name='entity_pers_person__bc6179_idx',
            old_name='entity_persons_person_idx',
        ),
        migrations.RenameIndex(
            model_name='label',
            new_name='labels_name_d8f370_idx',
            old_name='labels_name_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='persons_name_9c6d3a_idx',
            old_name='persons_name_idx',
        ),
        migrations.AddField(
            model_name='update',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='type',
            field=models.CharField(db_index=True, default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='entitylabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entityperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='update',
            index=models.Index(fields=['entity_id', 'activity_type'], name='updates_entity__6d0c5f_idx'),
        ),
    ]
