# Generated by Django 6.0.1 on 2026-01-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pm', '0013_make_status_fk_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLabelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pm_entity_label_link',
            },
        ),
        migrations.CreateModel(
            name='EntityPersonLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pm_entity_person_link',
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50)),
                ('updated', models.CharField(blank=True, max_length=50)),
                ('due_date_dt', models.DateField(blank=True, null=True)),
                ('schedule_start_dt', models.DateTimeField(blank=True, null=True)),
                ('schedule_end_dt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('seq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('is_inbox_epic', models.BooleanField(default=False)),
                ('notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'pm_epic',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50)),
                ('updated', models.CharField(blank=True, max_length=50)),
                ('due_date_dt', models.DateField(blank=True, null=True)),
                ('schedule_start_dt', models.DateTimeField(blank=True, null=True)),
                ('schedule_end_dt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('seq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'pm_note',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50)),
                ('updated', models.CharField(blank=True, max_length=50)),
                ('due_date_dt', models.DateField(blank=True, null=True)),
                ('schedule_start_dt', models.DateTimeField(blank=True, null=True)),
                ('schedule_end_dt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('seq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('stats_version', models.IntegerField(blank=True, null=True)),
                ('stats_updated', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'pm_project',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50)),
                ('updated', models.CharField(blank=True, max_length=50)),
                ('due_date_dt', models.DateField(blank=True, null=True)),
                ('schedule_start_dt', models.DateTimeField(blank=True, null=True)),
                ('schedule_end_dt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('seq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'pm_subtask',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created', models.CharField(blank=True, max_length=50)),
                ('updated', models.CharField(blank=True, max_length=50)),
                ('due_date_dt', models.DateField(blank=True, null=True)),
                ('schedule_start_dt', models.DateTimeField(blank=True, null=True)),
                ('schedule_end_dt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('seq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'pm_task',
            },
        ),
        # Remove index if it exists (safe operation)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS entities_status_1c41cf_idx;",
            reverse_sql="",  # No need to recreate in reverse
        ),
        # Note: Skipping AlterField for Entity.status_fk to avoid rebuild issues
        # The field is already a ForeignKey, just not with NOT NULL constraint in DB
        # This will be cleaned up in a later migration
        migrations.AddField(
            model_name='entitylabellink',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entitylabellink',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='pm.label'),
        ),
        migrations.AddField(
            model_name='entitypersonlink',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='entitypersonlink',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='pm.person'),
        ),
        migrations.AddField(
            model_name='epic',
            name='status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entities', to='pm.status'),
        ),
        migrations.AddField(
            model_name='note',
            name='status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entities', to='pm.status'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entities', to='pm.status'),
        ),
        migrations.AddField(
            model_name='epic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='pm.project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pm.epic'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pm.project'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entities', to='pm.status'),
        ),
        migrations.AddField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pm.epic'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pm.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entities', to='pm.status'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='pm.task'),
        ),
        migrations.AddIndex(
            model_name='entitylabellink',
            index=models.Index(fields=['content_type', 'object_id'], name='pm_entity_l_content_6ace16_idx'),
        ),
        migrations.AddIndex(
            model_name='entitylabellink',
            index=models.Index(fields=['label'], name='pm_entity_l_label_i_241304_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitylabellink',
            unique_together={('content_type', 'object_id', 'label')},
        ),
        migrations.AddIndex(
            model_name='entitypersonlink',
            index=models.Index(fields=['content_type', 'object_id'], name='pm_entity_p_content_dbae03_idx'),
        ),
        migrations.AddIndex(
            model_name='entitypersonlink',
            index=models.Index(fields=['person'], name='pm_entity_p_person__e878d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitypersonlink',
            unique_together={('content_type', 'object_id', 'person')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status_fk'], name='pm_note_status__1131cd_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['archived'], name='pm_note_archive_3e8083_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status_fk'], name='pm_project_status__823f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['archived'], name='pm_project_archive_da3adb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['seq_id'], name='pm_project_seq_id_e22fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='epic',
            index=models.Index(fields=['project'], name='pm_epic_project_1ce4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='epic',
            index=models.Index(fields=['status_fk'], name='pm_epic_status__993eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='epic',
            index=models.Index(fields=['archived'], name='pm_epic_archive_cbed6b_idx'),
        ),
        migrations.AddIndex(
            model_name='epic',
            index=models.Index(fields=['is_inbox_epic'], name='pm_epic_is_inbo_99dfc4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='pm_task_project_aeb2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['epic'], name='pm_task_epic_id_8b25c1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status_fk'], name='pm_task_status__f8f9df_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date_dt'], name='pm_task_due_dat_dea7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['archived'], name='pm_task_archive_8e8b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task'], name='pm_subtask_task_id_e425d8_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['project'], name='pm_subtask_project_2adf1e_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['epic'], name='pm_subtask_epic_id_4aa24c_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['status_fk'], name='pm_subtask_status__744fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['due_date_dt'], name='pm_subtask_due_dat_a48477_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['archived'], name='pm_subtask_archive_959a5b_idx'),
        ),
    ]
