# Generated by Django 6.0.1 on 2026-01-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0018_remove_old_entity_tables'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_type_3f73d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_status_1c41cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_due_dat_e4eacf_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_project_1dbbf6_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_updated_d9acc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_status__c0e5d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_due_dat_e78f58_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_archive_3148d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='entities_seq_id_2c53b6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='entitylabel',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='entitylabel',
            name='entity_labe_entity__24286c_idx',
        ),
        migrations.RemoveIndex(
            model_name='entitylabel',
            name='entity_labe_label_i_c81544_idx',
        ),
        migrations.AlterUniqueTogether(
            name='entityperson',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='entityperson',
            name='entity_pers_entity__9ace1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='entityperson',
            name='entity_pers_person__bc6179_idx',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='status_fk',
        ),
        migrations.RemoveField(
            model_name='entityperson',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entityperson',
            name='person',
        ),
        migrations.DeleteModel(
            name='EntityLabel',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityPerson',
        ),
    ]
