# Generated by Django 6.0.1 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0019_remove_entity_entities_type_3f73d9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependencies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subtask',
            name='dependencies',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
