# Generated by Django 6.0.1 on 2026-02-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='linked_entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
