# Generated by Django 6.0.1 on 2026-02-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_journalentry_linked_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='pending_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pending_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='pending_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pending_reason',
            field=models.TextField(blank=True),
        ),
    ]
