# Generated by Django 6.0.1 on 2026-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0024_epic_pending_reason_note_pending_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='pending_reason',
            field=models.BooleanField(default=False),
        ),
    ]
